var incompleteFields = ""; // Initialize variable for incomplete fields message

// Mapping of internal field names to user-friendly names
var friendlyNames = {
    "DenumireUnic": "Denumire Unică",
    "CUIUnic": "Cod Unic de Înregistrare",
    "ProfitB2": "Profit Net",
    "CifraB2": "Cifra de Afaceri",
    "RegiuneListB2": "Regiune",
    "JudetListB2": "Județ",
    "LocalitateListB2": "Localitate",
    "CodPostalB2": "Cod Poștal",
    "StradaB2": "Strada",
    "NrB2": "Număr",
    "TelefonB2": "Telefon",
    "EmailB2": "E-mail",
    "NumeB2": "Nume",
    "PrenumeB2": "Prenume",
    "FunctieB2": "Funcție",
    "DataNasteriiB2": "Data Nașterii",
    "CNPB2": "CNP",
    "BIB2": "Buletin de Identitate",
    "CIB2": "Carte de Identitate",
    "PasaportB2": "Pașaport",
    "SeriaB2": "Seria",
    "NumarB2": "Număr",
    "EliberatB2": "Eliberat",
    "DeCatreB2": "Eliberat de Către",
    "ValabilB2": "Valabil Până La",
    "DenumireBancaB3": "Denumire Bancă",
    "DenumireSucursalaB3": "Denumire Sucursală",
    "AdresaB3": "Adresă",
    "IBANB3": "IBAN",
    "TItularB3": "Titular",
    "TitluProiectC1": "Titlu Proiect",
    "DaC3": "Da (Întrebare C3)",
    "NuC3": "Nu (Întrebare C3)",
    "NationalC3": "Proiect Național",
    "EuropeanC3": "Proiect European",
    "InternationalC3": "Proiect Internațional",
    "DenumireC3": "Denumire Proiect",
    "NProiecteC3": "Număr de Proiecte",
    "DBeneficiarC3": "Denumire Beneficiar",
    "InDerulareC3": "Proiect În Derulare",
    "FinalizatC3": "Proiect Finalizat",
    "DataFInalizariiC3": "Data Finalizării",
    "ValNerambursabilaC3": "Valoare Nerambursabilă",
    "DescriereInvestitieC4": "Descriere Investiție",
    "ObiectiveProiectC5": "Obiectivele Proiectului",
    "RezultateAsteptateC6": "Rezultate Așteptate",
    "RiscuriIdentificateC7": "Riscuri Identificate",
    "PrincipiOrizontaleC8": "Principii Orizontale",
    "InstalareR3C5": "Instalare Activitate R3 C5",
    "InstalareR4C5": "Instalare Activitate R4 C5",
    "InstalareR3C6": "Instalare Activitate R3 C6",
    "InstalareR4C6": "Instalare Activitate R4 C6",
    "InformareR3C6": "Informare Activitate R3 C6",
    "CertificatR4C6": "Certificat Activitate R4 C6",
    "CertificatR5C6": "Certificat Activitate R5 C6",
    "CertificatR6C6": "Certificat Activitate R6 C6",
    "ContributieC11": "Contribuție",
    "DurataProiectuluiC12": "Durata Proiectului",
    "NumeD": "Nume", 
    "PrenumeD": "Prenume", 
    "CNPD": "CNP", 
    "RegiuneD": "Regiune", 
    "JudetD": "Județ", 
    "LocalitateD": "Localitate", 
    "StradaD": "Strada", 
    "NrD": "Număr", 
    "CodPostalD": "Cod Poștal", 
    "InitialD": "Inițial", 
    "PropusD": "Propus",
    "CUIB2": "Cod Unic de Înregistrare B",
    "ProfitP": "Profit Partener",
    "CifraP": "Cifra de Afaceri Partener",
    "RegiunePartener": "Regiune Partener",
    "JudetPartener": "Județ Partener",
    "LocalitatePartener": "Localitate Partener",
    "CodPostalPartener": "Cod Poștal Partener",
    "StradaPartener": "Strada Partener",
    "NrPartener": "Număr Partener",
    "TelefonPartener": "Telefon Partener",
    "EmailPartener": "E-mail Partener",
    "NumePartener": "Nume Partener",
    "PrenumePartener": "Prenume Partener",
    "FunctiePartner": "Funcție Partener",
    "DataNPartener": "Data Nașterii Partener",
    "CNPPartener": "CNP Partener",
    "BIPartener": "Buletin de Identitate Partener",
    "CIPartener": "Carte de Identitate Partener",
    "PasaportPartener": "Pașaport Partener",
    "SeriaPartener": "Seria Partener",
    "NumarPartener": "Număr Partener",
    "EliberatPartener": "Eliberat Partener",
    "DeCatrePartener": "Eliberat de Către Partener",
    "ValabilPartener": "Valabil Până La Partener",
    "BancaB3": "Denumire Bancă B",
    "SucursalaB3": "Denumire Sucursală B",
    "AdresaB3": "Adresă B",
    "TItularB3": "Titular B",
    "TitluProiectC1": "Titlu Proiect",
    "DenumireProgramC3": "Denumire Program Proiect",
    "NumarProiecteC3": "Număr de Proiecte Proiect",
    "DenumireBeneficiarC3": "Denumire Beneficiar Proiect",
    "DataFinalC3": "Data Finalizării Proiect",
    "ValoareC3": "Valoare Proiect",
    "SuprafataD": "Suprafață" 
    // Add more fields as needed
};

// Manually define the paths to all mandatory fields
var mandatoryFieldPaths = [
    "Page1.DenumireB2",
    "Page1.CUIB2",
    "Page1.Table1.Row2.ProfitB2",
    "Page1.Table1.Row2.CifraB2",
    "Page2.Table2.Row2.RegiuneListUnic",
    "Page2.Table2.Row2.JudetUnic",
    "Page2.Table2.Row2.LocalitateUnic",
    "Page2.Table3.Row2.CodPostalUnic",
    "Page2.Table3.Row2.StradaUnic",
    "Page2.Table3.Row2.NrUnic",
    "Page2.Table4.Row2.TelefonUnic",
    "Page2.Table4.Row2.EmailUnic",
    "Page2.Table5.Row2.NumeUnic",
    "Page2.Table5.Row2.PrenumeUnic",
    "Page2.Table5.Row2.FunctieUnic",
    "Page2.Table6.Row2.DataNUnic",
    "Page2.Table6.Row2.CNPUnic",
    "Page2.Table7.Row2.BIUnic",
    "Page2.Table7.Row2.CIUnic",
    "Page2.Table7.Row2.PasaportUnic",
    "Page2.Table7.Row2.SeriaUnic",
    "Page2.Table7.Row2.NumarUnic",
    "Page2.Table7.Row2.EliberatUnic",
    "Page2.Table7.Row2.DeCatreUnic",
    "Page2.Table7.Row2.ValabilUnic",
    "Page3.DenumirePartener",
    "Page3.CUIPartener",
    "Page3.Table1.Row2.ProfitP",
    "Page3.Table1.Row2.CifraP",
    "Page3.Table2.Row2.RegiunePartener",
    "Page3.Table2.Row2.JudetPartener",
    "Page3.Table2.Row2.LocalitatePartener",
    "Page3.Table3.Row2.CodPostalPartener",
    "Page3.Table3.Row2.StradaPartener",
    "Page3.Table3.Row2.NrPartener",
    "Page3.Table4.Row2.TelefonPartener",
    "Page3.Table4.Row2.EmailPartener",
    "Page3.Table5.Row2.NumePartener",
    "Page3.Table5.Row2.PrenumePartener",
    "Page3.Table5.Row2.FunctiePartner",
    "Page3.Table6.Row2.DataNPartener",
    "Page3.Table6.Row2.CNPPartener",
    "Page3.Table7.Row2.BIPartener",
    "Page3.Table7.Row2.CIPartener",
    "Page3.Table7.Row2.PasaportPartener",
    "Page3.Table7.Row2.SeriaPartener",
    "Page3.Table7.Row2.NumarPartener",
    "Page3.Table7.Row2.EliberatPartener",
    "Page3.Table7.Row2.DeCatrePartener",
    "Page3.Table7.Row2.ValabilPartener",
    "Page4.Table8.Row2.BancaB3",
    "Page4.Table8.Row2.SucursalaB3",
    "Page4.Table9.Row2.AdresaB3",
    "Page4.Table10.Row2.IBANB3",
    "Page4.Table10.Row2.TItularB3",
    "Page5.TitluProiectC1",
    "Page5.DaC3",
    "Page5.NuC3",
    "Page5.Tabel12Subform.Table12.Row2.Table14.Row1.NationalC3",
    "Page5.Tabel12Subform.Table12.Row2.Table14.Row2.EuropeanC3",
    "Page5.Tabel12Subform.Table12.Row2.Table14.Row3.InternationalC3",
    "Page5.Tabel12Subform.Table12.Row2.DenumireProgramC3",
    "Page5.Tabel12Subform.Table12.Row2.NumarProiecteC3",
    "Page5.Tabel12Subform.Table12.Row2.DenumireBeneficiarC3",
    "Page5.Tabel12Subform.Table12.Row2.Table15.Row1.InDerulareC3",
    "Page5.Tabel12Subform.Table12.Row2.Table15.Row2.FinalizatC3",
    "Page5.Tabel12Subform.Table12.Row2.Table15.Row3.DataFinalC3",
    "Page5.Tabel12Subform.Table12.Row2.ValoareC3",
    "Page6.DescriereC4",
    "Page6.ObiectiveC5",
    "Page6.RezultateC6",
    "Page6.RiscuriC7",
    "Page6.PrincipiiC8",
    "Page7.Table17.Row3.ActR1C5",
    "Page7.Table17.Row4.ActR2C5",
    "Page7.Table17.Row5.ActR3C5",
    "Page7.Table17.Row6.ActR4C5",
    "Page7.Table17.Row7.ActR5C5",
    "Page7.Table17.Row8.ActR6C5",
    "Page7.Table17.Row3.ActR1C6",
    "Page7.Table17.Row4.ActR2C6",
    "Page7.Table17.Row5.ActR3C6",
    "Page7.Table17.Row6.ActR4C6",
    "Page7.Table17.Row7.ActR5C6",
    "Page7.Table17.Row8.ActR6C6",
    "Page8.Table18.Row3.Informare6",
    "Page8.Table18.Row4.Cerificate6",
    "Page9.ContributiaC11",
    "Page9.DurataC12",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row2.NumeD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row2.PrenumeD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row2.CNPD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row4.RegiuneD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row4.JudetD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row4.LocalitateD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row6.StradaD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row6.NrD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row6.CodPostalD",
    "Page9.Tabel19subform.Table19.Row1.Table27.Row6[2].SuprafataD", 
    "Page9.Tabel19subform.Table19.Row1.Table27.Row6[2].Table28.Row1.Table29.Row2.InitialD",   
    "Page9.Tabel19subform.Table19.Row1.Table27.Row6[2].Table28.Row1.Table30.Row2.PropusFinalD"   
];

// Loop through each mandatory field path
for (var i = 0; i < mandatoryFieldPaths.length; i++) {
    var fieldPath = mandatoryFieldPaths[i];
    var field = xfa.resolveNode(fieldPath);
    
    // Check if the field is found
    if (field != null) {
        // Check if the field is mandatory and empty
        if (field.mandatory === "error" && (!field.rawValue || field.rawValue === "")) {
            // Extract the page number from the field path
            var pageMatch = fieldPath.match(/Page(\d+)/);
            var pageNumber = pageMatch ? pageMatch[1] : "unknown";
            
            // Use friendly name if available, otherwise fall back to the internal name
            var friendlyName = friendlyNames[field.name] || field.name;
            incompleteFields += "Campul \"" + friendlyName + "\" pe Pagina \"" + pageNumber + "\" este obligatoriu!\n";  
        }
    } else {
        incompleteFields += "Campul la calea \"" + fieldPath + "\" nu există.\n";
    }
}

// Display a message if there are incomplete fields
if (incompleteFields !== "") {
    xfa.host.messageBox("Urmatoarele campuri sunt necompletate:\n" + incompleteFields, "Campuri Incomplete", 3);
} else {
    xfa.host.messageBox("Toate campurile obligatorii sunt completate.", "Validare completa!", 3);
}
